# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1bf232743d719e1461ee4227d3b5b280e1bd68965503672e08868c12640d412939720c1489f197ad58e008e4fb52c12c48a81752b47ef437d9a8f934fad77026
  steam_api_key: <%= ENV["STEAM_API_KEY"] %>

test:
  secret_key_base: 2caccef2de1eecb7dc0f46ac371548413a3c13716912b8558c96b708d2ec854f3b837bf00b212852f7225bbb27936604bad5635820ff20de9d1630b0c272794d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  steam_api_key: <%= ENV["STEAM_API_KEY"] %>
